Algoritmo "semnome"

Var

user,password: caractere

Inicio

      escreva("digite seu usuário :")
      leia(user)
      escreva("digite sua senha:")
      leia(password)

enquanto (user <> "admin") ou (password <> "admin") faca
              escreval("usuário ou senha inválidos")
              escreva("digite seu usuário :")
              leia(user)
              escreva("digite sua senha:")
              leia(password)
fimenquanto
 escreval("seja bem vindo ao sistema")

Fimalgoritmo